/*
###############################################################
#  Generated by:      Cadence Innovus 17.10-p006_1
#  OS:                Linux x86_64(Host ID engnx03a.utdallas.edu)
#  Generated on:      Wed May  1 04:00:24 2024
#  Design:            Top_alu
#  Command:           saveNetlist f4_innovas.v
###############################################################
*/
/////////////////////////////////////////////////////////////
// Created by: Synopsys DC Expert(TM) in wire load mode
// Version   : O-2018.06-SP1
// Date      : Wed May  1 03:46:01 2024
/////////////////////////////////////////////////////////////
module INVERTER (
	IN, 
	OUT);
   input IN;
   output OUT;
endmodule

module NAND (
	A, 
	B, 
	OUT);
   input A;
   input B;
   output OUT;
endmodule

module NOR (
	A, 
	B, 
	OUT);
   input A;
   input B;
   output OUT;
endmodule

module XOR (
	A, 
	B, 
	OUT);
   input A;
   input B;
   output OUT;
endmodule

module AOI22 (
	A, 
	B, 
	C, 
	D, 
	OUT);
   input A;
   input B;
   input C;
   input D;
   output OUT;
endmodule

module DFF (
	D, 
	CLK, 
	Q);
   input D;
   input CLK;
   output Q;
endmodule

module Top_alu (
	A, 
	Inst, 
	RESET, 
	clk, 
	OUT);
   input [3:0] A;
   input [1:0] Inst;
   input RESET;
   input clk;
   output [3:0] OUT;

   // Internal wires
   wire N18;
   wire N19;
   wire N21;
   wire N22;
   wire N23;
   wire N24;
   wire N25;
   wire N26;
   wire N27;
   wire N28;
   wire N29;
   wire N31;
   wire N32;
   wire N33;
   wire N37;
   wire N38;
   wire N39;
   wire N45;
   wire N46;
   wire N47;
   wire N49;
   wire N50;
   wire N51;
   wire N52;
   wire N53;
   wire N54;
   wire N55;
   wire N59;
   wire N60;
   wire N61;
   wire N74;
   wire N75;
   wire N76;
   wire N77;
   wire N82;
   wire N83;
   wire N84;
   wire N85;
   wire N86;
   wire N87;
   wire N88;
   wire N89;
   wire m1;
   wire m2;
   wire m3;
   wire m4;
   wire m5;
   wire m6;
   wire m7;
   wire m8;
   wire m9;
   wire m10;
   wire m11;
   wire m12;
   wire m13;
   wire m14;
   wire m15;
   wire m16;
   wire m17;
   wire m18;
   wire m19;
   wire m20;
   wire m21;
   wire m22;
   wire m23;
   wire m24;
   wire m25;
   wire m26;
   wire m27;
   wire m28;
   wire m29;
   wire m30;
   wire m31;
   wire m32;
   wire m33;
   wire m34;
   wire m35;
   wire m36;
   wire m37;
   wire m38;
   wire m39;
   wire m40;
   wire m41;
   wire m42;
   wire m43;
   wire m44;
   wire m45;
   wire m46;
   wire m47;
   wire m48;
   wire m49;
   wire m50;
   wire m51;
   wire \add_sub/c2 ;
   wire \add_sub/c1 ;
   wire \add_sub/c0 ;
   wire \add_sub/fa0/c2 ;
   wire \add_sub/fa0/c1 ;
   wire \add_sub/fa0/s1 ;
   wire \add_sub/fa3/s1 ;
   wire \add_sub/fa2/c2 ;
   wire \add_sub/fa2/c1 ;
   wire \add_sub/fa2/s1 ;
   wire \add_sub/fa1/c2 ;
   wire \add_sub/fa1/c1 ;
   wire \add_sub/fa1/s1 ;
   wire [3:0] sum;
   wire [3:0] \add_sub/w1 ;

   assign N21 = A[3] ;

   XOR C169 (.A(A[0]),
	.B(OUT[0]),
	.OUT(N89));
   INVERTER I_21 (.IN(N89),
	.OUT(N77));
   XOR C167 (.A(A[1]),
	.B(OUT[1]),
	.OUT(N88));
   INVERTER I_20 (.IN(N88),
	.OUT(N76));
   XOR C165 (.A(A[2]),
	.B(OUT[2]),
	.OUT(N87));
   INVERTER I_19 (.IN(N87),
	.OUT(N75));
   XOR C163 (.A(N21),
	.B(OUT[3]),
	.OUT(N86));
   INVERTER I_18 (.IN(N86),
	.OUT(N74));
   NAND C161 (.A(A[0]),
	.B(OUT[3]),
	.OUT(m1));
   NAND C160 (.A(A[1]),
	.B(OUT[2]),
	.OUT(m2));
   NAND C159 (.A(A[1]),
	.B(OUT[3]),
	.OUT(m3));
   NAND C158 (.A(A[2]),
	.B(OUT[3]),
	.OUT(m4));
   INVERTER I_16 (.IN(N54),
	.OUT(N55));
   INVERTER I_15 (.IN(A[0]),
	.OUT(N52));
   INVERTER I_14 (.IN(N50),
	.OUT(N51));
   INVERTER I_12 (.IN(N46),
	.OUT(N47));
   NAND C145 (.A(A[0]),
	.B(OUT[0]),
	.OUT(m5));
   NAND C144 (.A(A[1]),
	.B(OUT[0]),
	.OUT(m6));
   NAND C143 (.A(A[1]),
	.B(OUT[1]),
	.OUT(m7));
   NAND C142 (.A(A[2]),
	.B(OUT[0]),
	.OUT(m8));
   INVERTER I_9 (.IN(N32),
	.OUT(N33));
   INVERTER I_7 (.IN(N28),
	.OUT(N29));
   INVERTER I_6 (.IN(A[1]),
	.OUT(N26));
   INVERTER I_5 (.IN(N24),
	.OUT(N25));
   INVERTER I_4 (.IN(A[2]),
	.OUT(N22));
   INVERTER I_2 (.IN(Inst[1]),
	.OUT(N19));
   NAND C117 (.A(A[0]),
	.B(OUT[1]),
	.OUT(m9));
   NAND C116 (.A(A[0]),
	.B(OUT[2]),
	.OUT(m10));
   NAND C115 (.A(Inst[1]),
	.B(Inst[0]),
	.OUT(N18));
   NAND C65 (.A(N22),
	.B(N26),
	.OUT(N53));
   NAND C61 (.A(N22),
	.B(A[1]),
	.OUT(N49));
   NAND C57 (.A(A[2]),
	.B(N26),
	.OUT(N45));
   NAND C35 (.A(N22),
	.B(N26),
	.OUT(N31));
   NAND C31 (.A(N22),
	.B(A[1]),
	.OUT(N27));
   NAND C27 (.A(A[2]),
	.B(N26),
	.OUT(N23));
   DFF \OUT_reg[0]  (.D(N82),
	.CLK(clk),
	.Q(OUT[0]));
   DFF \OUT_reg[3]  (.D(N85),
	.CLK(clk),
	.Q(OUT[3]));
   DFF \OUT_reg[1]  (.D(N83),
	.CLK(clk),
	.Q(OUT[1]));
   DFF \OUT_reg[2]  (.D(N84),
	.CLK(clk),
	.Q(OUT[2]));
   NAND U3 (.A(m11),
	.B(m12),
	.OUT(N85));
   NAND U4 (.A(sum[3]),
	.B(m13),
	.OUT(m12));
   AOI22 U5 (.A(m14),
	.B(m15),
	.C(m16),
	.D(N74),
	.OUT(m11));
   NAND U6 (.A(m17),
	.B(m18),
	.OUT(m15));
   NAND U7 (.A(N33),
	.B(m19),
	.OUT(m18));
   AOI22 U8 (.A(N25),
	.B(N37),
	.C(N29),
	.D(N38),
	.OUT(m17));
   NAND U9 (.A(m20),
	.B(m21),
	.OUT(N84));
   AOI22 U10 (.A(m22),
	.B(N55),
	.C(m14),
	.D(m23),
	.OUT(m21));
   INVERTER U11 (.IN(m24),
	.OUT(m23));
   AOI22 U12 (.A(N29),
	.B(N39),
	.C(N33),
	.D(m25),
	.OUT(m24));
   NOR U13 (.A(m1),
	.B(m26),
	.OUT(m22));
   AOI22 U14 (.A(m16),
	.B(N75),
	.C(sum[2]),
	.D(m13),
	.OUT(m20));
   NAND U15 (.A(m27),
	.B(m28),
	.OUT(N83));
   AOI22 U16 (.A(m29),
	.B(m14),
	.C(m30),
	.D(m31),
	.OUT(m28));
   INVERTER U17 (.IN(m32),
	.OUT(m31));
   AOI22 U18 (.A(N51),
	.B(N60),
	.C(N55),
	.D(m19),
	.OUT(m32));
   INVERTER U19 (.IN(m10),
	.OUT(m19));
   NOR U20 (.A(m33),
	.B(N21),
	.OUT(m14));
   NOR U21 (.A(m5),
	.B(m34),
	.OUT(m29));
   INVERTER U22 (.IN(N33),
	.OUT(m34));
   AOI22 U23 (.A(m16),
	.B(N76),
	.C(sum[1]),
	.D(m13),
	.OUT(m27));
   NAND U24 (.A(m35),
	.B(m36),
	.OUT(N82));
   NAND U25 (.A(sum[0]),
	.B(m13),
	.OUT(m36));
   INVERTER U26 (.IN(m37),
	.OUT(m13));
   NAND U27 (.A(m38),
	.B(N19),
	.OUT(m37));
   NOR U28 (.A(RESET),
	.B(m39),
	.OUT(m38));
   INVERTER U29 (.IN(N18),
	.OUT(m39));
   AOI22 U30 (.A(m30),
	.B(m40),
	.C(m16),
	.D(N77),
	.OUT(m35));
   NOR U31 (.A(N18),
	.B(RESET),
	.OUT(m16));
   NAND U32 (.A(m41),
	.B(m42),
	.OUT(m40));
   NAND U33 (.A(N55),
	.B(m25),
	.OUT(m42));
   INVERTER U34 (.IN(m9),
	.OUT(m25));
   AOI22 U35 (.A(N47),
	.B(N59),
	.C(N51),
	.D(N61),
	.OUT(m41));
   INVERTER U36 (.IN(m26),
	.OUT(m30));
   NAND U37 (.A(N21),
	.B(m43),
	.OUT(m26));
   INVERTER U38 (.IN(m33),
	.OUT(m43));
   NAND U39 (.A(m44),
	.B(N18),
	.OUT(m33));
   NOR U40 (.A(RESET),
	.B(N19),
	.OUT(m44));
   NAND U41 (.A(m45),
	.B(m46),
	.OUT(N54));
   INVERTER U42 (.IN(N53),
	.OUT(m45));
   NAND U43 (.A(N52),
	.B(m47),
	.OUT(N50));
   INVERTER U44 (.IN(N49),
	.OUT(m47));
   NAND U45 (.A(N52),
	.B(m48),
	.OUT(N46));
   INVERTER U46 (.IN(N45),
	.OUT(m48));
   NAND U47 (.A(m46),
	.B(m49),
	.OUT(N32));
   INVERTER U48 (.IN(N31),
	.OUT(m49));
   INVERTER U49 (.IN(N52),
	.OUT(m46));
   NAND U50 (.A(N52),
	.B(m50),
	.OUT(N28));
   INVERTER U51 (.IN(N27),
	.OUT(m50));
   NAND U52 (.A(N52),
	.B(m51),
	.OUT(N24));
   INVERTER U53 (.IN(N23),
	.OUT(m51));
   INVERTER U54 (.IN(m8),
	.OUT(N37));
   INVERTER U55 (.IN(m7),
	.OUT(N38));
   INVERTER U56 (.IN(m6),
	.OUT(N39));
   INVERTER U57 (.IN(m4),
	.OUT(N59));
   INVERTER U58 (.IN(m3),
	.OUT(N60));
   INVERTER U59 (.IN(m2),
	.OUT(N61));
   XOR \add_sub/C10  (.A(A[0]),
	.B(Inst[0]),
	.OUT(\add_sub/w1 [0]));
   XOR \add_sub/C11  (.A(A[1]),
	.B(Inst[0]),
	.OUT(\add_sub/w1 [1]));
   XOR \add_sub/C12  (.A(A[2]),
	.B(Inst[0]),
	.OUT(\add_sub/w1 [2]));
   XOR \add_sub/C13  (.A(N21),
	.B(Inst[0]),
	.OUT(\add_sub/w1 [3]));
   XOR \add_sub/fa0/U2  (.A(\add_sub/w1 [0]),
	.B(OUT[0]),
	.OUT(\add_sub/fa0/s1 ));
   XOR \add_sub/fa0/U1  (.A(Inst[0]),
	.B(\add_sub/fa0/s1 ),
	.OUT(sum[0]));
   NAND \add_sub/fa0/nand1  (.A(\add_sub/fa0/s1 ),
	.B(Inst[0]),
	.OUT(\add_sub/fa0/c1 ));
   NAND \add_sub/fa0/nand2  (.A(OUT[0]),
	.B(\add_sub/w1 [0]),
	.OUT(\add_sub/fa0/c2 ));
   NAND \add_sub/fa0/nand3  (.A(\add_sub/fa0/c1 ),
	.B(\add_sub/fa0/c2 ),
	.OUT(\add_sub/c0 ));
   XOR \add_sub/fa3/U2  (.A(\add_sub/w1 [3]),
	.B(OUT[3]),
	.OUT(\add_sub/fa3/s1 ));
   XOR \add_sub/fa3/U1  (.A(\add_sub/c2 ),
	.B(\add_sub/fa3/s1 ),
	.OUT(sum[3]));
   XOR \add_sub/fa2/U2  (.A(\add_sub/w1 [2]),
	.B(OUT[2]),
	.OUT(\add_sub/fa2/s1 ));
   XOR \add_sub/fa2/U1  (.A(\add_sub/c1 ),
	.B(\add_sub/fa2/s1 ),
	.OUT(sum[2]));
   NAND \add_sub/fa2/nand1  (.A(\add_sub/fa2/s1 ),
	.B(\add_sub/c1 ),
	.OUT(\add_sub/fa2/c1 ));
   NAND \add_sub/fa2/nand2  (.A(OUT[2]),
	.B(\add_sub/w1 [2]),
	.OUT(\add_sub/fa2/c2 ));
   NAND \add_sub/fa2/nand3  (.A(\add_sub/fa2/c1 ),
	.B(\add_sub/fa2/c2 ),
	.OUT(\add_sub/c2 ));
   XOR \add_sub/fa1/U2  (.A(\add_sub/w1 [1]),
	.B(OUT[1]),
	.OUT(\add_sub/fa1/s1 ));
   XOR \add_sub/fa1/U1  (.A(\add_sub/c0 ),
	.B(\add_sub/fa1/s1 ),
	.OUT(sum[1]));
   NAND \add_sub/fa1/nand1  (.A(\add_sub/fa1/s1 ),
	.B(\add_sub/c0 ),
	.OUT(\add_sub/fa1/c1 ));
   NAND \add_sub/fa1/nand2  (.A(OUT[1]),
	.B(\add_sub/w1 [1]),
	.OUT(\add_sub/fa1/c2 ));
   NAND \add_sub/fa1/nand3  (.A(\add_sub/fa1/c1 ),
	.B(\add_sub/fa1/c2 ),
	.OUT(\add_sub/c1 ));
endmodule

